### ISSUE TITLE
Animal bite registry cant add patient

### ISSUE THREAD

**Issue by jeorgeBalmes** [KuyaGit/bangis#15]
diba yung idea tol is dapat nakakapagadd sya ng patient information kahit hindi filled yung tissues culture vaccine. so ayun tol di makapag add and dapat pag nagadd ka ng patient data dito is magrereflect sya sa lahat ng nacreate na agri accounts
![image](https://github.com/KuyaGit/bangis/assets/130200934/7e4e254e-d688-4c04-bae4-4f8f67ce3a16)

**Comment by KuyaGit** [comment]
> diba yung idea tol is dapat nakakapagadd sya ng patient information kahit hindi filled yung tissues culture vaccine. so ayun tol di makapag add and dapat pag nagadd ka ng patient data dito is magrereflect sya sa lahat ng nacreate na agri accounts ![image](https://private-user-images.githubusercontent.com/130200934/305784609-7e4e254e-d688-4c04-bae4-4f8f67ce3a16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTU0NzksIm5iZiI6MTcwODMxNTE3OSwicGF0aCI6Ii8xMzAyMDA5MzQvMzA1Nzg0NjA5LTdlNGUyNTRlLWQ2ODgtNGMwNC1iYWU0LTRmOGY2N2NlM2ExNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQwMzU5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MmMwY2Y4MDM5NTU5YmE2OTc4ZjhmZDc2ODk2Yjg5NDliNWUxMjkyZGNjNmY5MjI2ZDUxMDYyYTAyM2MyOGRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DndO9PgHjbGaU--D0XXHl7d96LcJ4KT_dDA9QWUXeUY)

sige tol wala naman nagsabi sa akin about na di need yung tissue culture vaccine fix ko later

**Comment by jeorgeBalmes** [comment]
sige tol yung tissues culture vaccine kasi ay kahit di muna kumpleto yung D0 D3 etc. vaccine kaya need lagyan ng edit button para pag bumalik yung patient for another dose ay edit nalang. salamat tol
