### ISSUE TITLE
Viewing ng data ng animal bite registry sa Agriculture sectors kulang ang fields

### ISSUE THREAD

**Issue by jeorgeBalmes** [KuyaGit/bangis#47]
Yung "Washing of Bite" at yung fields ng vaccine names hindi kita
![image](https://github.com/KuyaGit/bangis/assets/130200934/8032960e-1b9d-4fb4-889d-bc84ec053787)

**Comment by jeorgeBalmes** [comment]
i mean hindi kita yung laman ng fields sa vaccine names

**Comment by KuyaGit** [comment]
Internet issue Check your Internet. Kasi Need malakas net tas tinatry ko rin sya sa device ko sa nakadeploy ok naman yun lang hindi ok ay yung Wash After Bite
